-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 10:07:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema serviceAutomotor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `serviceAutomotor` ;

-- -----------------------------------------------------
-- Schema serviceAutomotor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `serviceAutomotor` ;
USE `serviceAutomotor` ;

-- -----------------------------------------------------
-- Table `serviceAutomotor`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`direccion` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`direccion` (
  `id_direccion` INT NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT(10) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  PRIMARY KEY (`id_direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`rol` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`rol` (
  `id_rol` INT(1) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`usuario` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`usuario` (
  `id_usuario` INT(2) NOT NULL,
  `correro` VARCHAR(64) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol_id_rol` INT NOT NULL,
  `direccion_id_direccion` INT NOT NULL,
  `rol_id_rol1` INT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`, `rol_id_rol`),
  INDEX `fk_usuario_direccion1_idx` (`direccion_id_direccion` ASC) VISIBLE,
  INDEX `fk_usuario_rol1_idx` (`rol_id_rol1` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_direccion1`
    FOREIGN KEY (`direccion_id_direccion`)
    REFERENCES `serviceAutomotor`.`direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id_rol1`)
    REFERENCES `serviceAutomotor`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`cliente` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `imagen` VARCHAR(100) NULL,
  `telefono` VARCHAR(45) NULL,
  `usuario_id_usuario` INT(2) NOT NULL,
  `usuario_rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `usuario_id_usuario`, `usuario_rol_id_rol`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id_usuario` ASC, `usuario_rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id_usuario` , `usuario_rol_id_rol`)
    REFERENCES `serviceAutomotor`.`usuario` (`id_usuario` , `rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`administrador` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`administrador` (
  `id_administrador` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `usuario_id_usuario` INT(2) NOT NULL,
  `usuario_rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_administrador`, `usuario_id_usuario`, `usuario_rol_id_rol`),
  INDEX `fk_administrador_usuario1_idx` (`usuario_id_usuario` ASC, `usuario_rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario_id_usuario` , `usuario_rol_id_rol`)
    REFERENCES `serviceAutomotor`.`usuario` (`id_usuario` , `rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`servicio` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`servicio` (
  `id_servicio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `serviciocol` VARCHAR(45) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `cliente_usuario_id_usuario` INT(2) NOT NULL,
  `cliente_usuario_rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_servicio`),
  INDEX `fk_servicio_cliente1_idx` (`cliente_id_cliente` ASC, `cliente_usuario_id_usuario` ASC, `cliente_usuario_rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_usuario_id_usuario` , `cliente_usuario_rol_id_rol`)
    REFERENCES `serviceAutomotor`.`cliente` (`id_cliente` , `usuario_id_usuario` , `usuario_rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`presupuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`presupuesto` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`presupuesto` (
  `id_presupuesto` INT NOT NULL,
  `total` DOUBLE NULL,
  PRIMARY KEY (`id_presupuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`vehiculo` (
  `id_vehiculo` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `patente` VARCHAR(45) NULL,
  `cliente_id_cliente` INT NOT NULL,
  `cliente_usuario_id_usuario` INT(2) NOT NULL,
  `cliente_usuario_rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_vehiculo`, `cliente_id_cliente`, `cliente_usuario_id_usuario`, `cliente_usuario_rol_id_rol`),
  INDEX `fk_vehiculo_cliente1_idx` (`cliente_id_cliente` ASC, `cliente_usuario_id_usuario` ASC, `cliente_usuario_rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_usuario_id_usuario` , `cliente_usuario_rol_id_rol`)
    REFERENCES `serviceAutomotor`.`cliente` (`id_cliente` , `usuario_id_usuario` , `usuario_rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`ordenReparacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`ordenReparacion` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`ordenReparacion` (
  `id_ordenReparacion` INT NOT NULL,
  `administrador_id_administrador` INT NOT NULL,
  `administrador_usuario_id_usuario` INT(2) NOT NULL,
  `administrador_usuario_rol_id_rol` INT NOT NULL,
  `vehiculo_id_vehiculo` INT NOT NULL,
  `vehiculo_cliente_id_cliente` INT NOT NULL,
  `vehiculo_cliente_usuario_id_usuario` INT(2) NOT NULL,
  `vehiculo_cliente_usuario_rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_ordenReparacion`),
  INDEX `fk_ordenReparacion_administrador1_idx` (`administrador_id_administrador` ASC, `administrador_usuario_id_usuario` ASC, `administrador_usuario_rol_id_rol` ASC) VISIBLE,
  INDEX `fk_ordenReparacion_vehiculo1_idx` (`vehiculo_id_vehiculo` ASC, `vehiculo_cliente_id_cliente` ASC, `vehiculo_cliente_usuario_id_usuario` ASC, `vehiculo_cliente_usuario_rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_ordenReparacion_administrador1`
    FOREIGN KEY (`administrador_id_administrador` , `administrador_usuario_id_usuario` , `administrador_usuario_rol_id_rol`)
    REFERENCES `serviceAutomotor`.`administrador` (`id_administrador` , `usuario_id_usuario` , `usuario_rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordenReparacion_vehiculo1`
    FOREIGN KEY (`vehiculo_id_vehiculo` , `vehiculo_cliente_id_cliente` , `vehiculo_cliente_usuario_id_usuario` , `vehiculo_cliente_usuario_rol_id_rol`)
    REFERENCES `serviceAutomotor`.`vehiculo` (`id_vehiculo` , `cliente_id_cliente` , `cliente_usuario_id_usuario` , `cliente_usuario_rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`turno` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`turno` (
  `id_turno` INT NOT NULL,
  `dia` DATE NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `ordenReparacion_id_ordenReparacion` INT NOT NULL,
  PRIMARY KEY (`id_turno`),
  INDEX `fk_turno_ordenReparacion1_idx` (`ordenReparacion_id_ordenReparacion` ASC) VISIBLE,
  CONSTRAINT `fk_turno_ordenReparacion1`
    FOREIGN KEY (`ordenReparacion_id_ordenReparacion`)
    REFERENCES `serviceAutomotor`.`ordenReparacion` (`id_ordenReparacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`servicio_has_presupuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`servicio_has_presupuesto` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`servicio_has_presupuesto` (
  `servicio_id_servicio` INT NOT NULL,
  `presupuesto_id_presupuesto` INT NOT NULL,
  PRIMARY KEY (`servicio_id_servicio`, `presupuesto_id_presupuesto`),
  INDEX `fk_servicio_has_presupuesto_presupuesto1_idx` (`presupuesto_id_presupuesto` ASC) VISIBLE,
  INDEX `fk_servicio_has_presupuesto_servicio1_idx` (`servicio_id_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_has_presupuesto_servicio1`
    FOREIGN KEY (`servicio_id_servicio`)
    REFERENCES `serviceAutomotor`.`servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_has_presupuesto_presupuesto1`
    FOREIGN KEY (`presupuesto_id_presupuesto`)
    REFERENCES `serviceAutomotor`.`presupuesto` (`id_presupuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `serviceAutomotor`.`servicio_has_turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `serviceAutomotor`.`servicio_has_turno` ;

CREATE TABLE IF NOT EXISTS `serviceAutomotor`.`servicio_has_turno` (
  `servicio_id_servicio` INT NOT NULL,
  `turno_id_turno` INT NOT NULL,
  PRIMARY KEY (`servicio_id_servicio`, `turno_id_turno`),
  INDEX `fk_servicio_has_turno_turno1_idx` (`turno_id_turno` ASC) VISIBLE,
  INDEX `fk_servicio_has_turno_servicio1_idx` (`servicio_id_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_has_turno_servicio1`
    FOREIGN KEY (`servicio_id_servicio`)
    REFERENCES `serviceAutomotor`.`servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_has_turno_turno1`
    FOREIGN KEY (`turno_id_turno`)
    REFERENCES `serviceAutomotor`.`turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
